db-host           = ${DB_HOST}
db-port           = ${DB_PORT}
db-name           = ${DB_NAME}
db-user           = ${DB_USER}
db-password       = ${DB_PASSWORD}
db-jdbc-url       = ${DB_JDBC_URL}
jwt-secret        = ${JWT_SECRET}
admin-password    = ${ADMIN_PASSWORD}
db-ssl            = true
db-ssl            = ${?DB_SSL}
db-admin-user     = ${DB_USER}
db-admin-user     = ${?DB_ADMIN_USER}
db-admin-password = ${DB_PASSWORD}
db-admin-password = ${?DB_ADMIN_PASSWORD}
google-client-id  = ""
google-client-id  = ${?GOOGLE_CLIENT_ID}
ses-region        = "us-west-2"
ses-region        = ${?SES_REGION}
from-email        = "noreply@contrapunctus.app"
from-email        = ${?FROM_EMAIL}
frontend-base-url = "https://www.contrapunctus.app"
frontend-base-url = ${?FRONTEND_BASE_URL}
